apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: expense-tracker-api
spec:
  selector:
    app: expense-tracker-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001 # You can choose any port from 30000-32767
