apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: expense-tracker-web
spec:
  selector:
    app: expense-tracker-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002 # You can choose any port from 30000-32767
